name: File Update Workflow

on:
  push:
    paths:
      - src/calculator/hello_calculator.py  # Trigger on specific file update
  workflow_dispatch:            # Allow manual triggering

jobs:
  save-file:
    runs-on: self-hosted  # Use your self-hosted runner

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3

      - name: Copy updated file to target directory
        run: |
          mkdir -p /home/ubuntu/runner/workfiles
          cp src/calculator/hello_calculator.py /home/ubuntu/runner/workfiles/
